#!/bin/sh
apt-cache show --no-all-versions icu-devtools 2>/dev/null| grep -E '^Version:|^Installed-Size:|^Size:' | awk '
{
  if($1=="Installed-Size:") is=$2*1024;
  else if($1=="Size:") ps=$2;
  else if($1=="Version:") v=$2;
}END{
  printf "%%s\n%%u\n%%u\n", v, ps, is
}'
