#!/bin/sh
CHECKUPDATES_DB="${TMPDIR:-/tmp}/checkup-db-$USER/"
DBPath="$(pacman-conf DBPath)"
mkdir -p "$CHECKUPDATES_DB"
ln -sf "$DBPath/local" "$CHECKUPDATES_DB" > /dev/null 2>&1
fakeroot pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null >/dev/null || exit $?
pacman -Qn --dbpath "$CHECKUPDATES_DB/" 2> /dev/null | cut -d ' ' -f1 | grep -v '\[.*\]'
